Traceback (most recent call last):
  File "/opt/jupyterhub/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/jupyterhub/lib/python3.8/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/jupyterhub/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/jupyterhub/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/jupyterhub/lib/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/opt/jupyterhub/lib/python3.8/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/jupyterhub/lib/python3.8/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from mip import Model, xsum, maximize, BINARY

p = [10, 13, 18, 31, 7, 15]
w = [11, 15, 20, 35, 10, 33]
c, I = 47, range(len(w))

m = Model("knapsack")

x = [m.add_var(var_type=BINARY) for i in I]

m.objective = maximize(xsum(p[i] * x[i] for i in I))

m += xsum(w[i] * x[i] for i in I) <= c

m.optimize(solver=GLPK(msg=True))

selected = [i for i in I if x[i].x >= 0.99]
print("selected items: {}".format(selected))

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-12-1f84f8ecca1b>[0m in [0;36m<module>[0;34m[0m
[1;32m      5[0m [0mc[0m[0;34m,[0m [0mI[0m [0;34m=[0m [0;36m47[0m[0;34m,[0m [0mrange[0m[0;34m([0m[0mlen[0m[0;34m([0m[0mw[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      6[0m [0;34m[0m[0m
[0;32m----> 7[0;31m [0mm[0m [0;34m=[0m [0mModel[0m[0;34m([0m[0;34m"knapsack"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      8[0m [0;34m[0m[0m
[1;32m      9[0m [0mx[0m [0;34m=[0m [0;34m[[0m[0mm[0m[0;34m.[0m[0madd_var[0m[0;34m([0m[0mvar_type[0m[0;34m=[0m[0mBINARY[0m[0;34m)[0m [0;32mfor[0m [0mi[0m [0;32min[0m [0mI[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/jupyterhub/lib/python3.8/site-packages/mip/model.py[0m in [0;36m__init__[0;34m(self, name, sense, solver_name, solver)[0m
[1;32m     96[0m                     [0mself[0m[0;34m.[0m[0msolver_name[0m [0;34m=[0m [0mmip[0m[0;34m.[0m[0mGUROBI[0m[0;34m[0m[0;34m[0m[0m
[1;32m     97[0m                 [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 98[0;31m                     [0;32mimport[0m [0mmip[0m[0;34m.[0m[0mcbc[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     99[0m [0;34m[0m[0m
[1;32m    100[0m                     [0mself[0m[0;34m.[0m[0msolver[0m [0;34m=[0m [0mmip[0m[0;34m.[0m[0mcbc[0m[0;34m.[0m[0mSolverCbc[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mname[0m[0;34m,[0m [0msense[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/jupyterhub/lib/python3.8/site-packages/mip/cbc.py[0m in [0;36m<module>[0;34m[0m
[1;32m    601[0m [0;34m[0m[0m
[1;32m    602[0m [0;34m[0m[0m
[0;32m--> 603[0;31m [0mOsi_getNumCols[0m [0;34m=[0m [0mcbclib[0m[0;34m.[0m[0mOsi_getNumCols[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    604[0m [0mOsi_getColSolution[0m [0;34m=[0m [0mcbclib[0m[0;34m.[0m[0mOsi_getColSolution[0m[0;34m[0m[0;34m[0m[0m
[1;32m    605[0m [0mOsi_getIntegerTolerance[0m [0;34m=[0m [0mcbclib[0m[0;34m.[0m[0mOsi_getIntegerTolerance[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'cbclib' is not defined
NameError: name 'cbclib' is not defined

